[package]
distribution = "2201.3.0"
name = "rainier_sample"
org = "sameera"
version = "0.1.0"

[build-options]
observabilityIncluded = true

# [persist.rainier.target.gsheets]
# sheetId = ""
# token = ""
# sheetName = ""

# [persist.rainier]
# moduleName = "rainier"
# clientTypes = ["MyRainierClient"]


[persist.rainier.storage.mysql]
host = ""
password = ""
port = 3307
user = ""
#database = "rainier"
